// AUTOGENERADO por tools/gen_parametros.py - NO editar a mano.
//
// Sale de firmware-pantalla/src/Interfaz.cpp y de contrato/ContratoHmi.h.
// Los controles de la app son los MISMOS que los de la pantalla, con el
// mismo paso, los mismos limites y el mismo formato, porque se derivan
// de ellos. Escritos dos veces divergen, y el dia que divergen la app
// deja poner un valor que el controlador recorta -y el operador ve un
// numero que no es el que puso-.
//
// Formatos: 0 entero - 1 decimas - 2 hh:mm - 3,4,5 «sin limite»
//           6 «apagada» bajo el minimo - 7 «sin techo»
window.PARAMETROS = {
  1: {t:"Objetivo (ppm)", k:"num", s:"CO2", paso:50, min:400, max:1500, f:0},
  2: {t:"Banda muerta (ppm)", k:"num", s:"CO2", paso:25, min:25, max:500, f:0},
  3: {t:"Inyeccion de CO2", k:"llave", s:"Que atiende cada demanda"},
  4: {t:"Minutos respecto de UTC", k:"num", s:"Conexion", paso:60, min:-720, max:840, f:0},
  5: {t:"Demora al arrancar", k:"num", s:"CO2", paso:15, min:0, max:240, f:0},
  6: {t:"Cortar antes de apagar", k:"num", s:"CO2", paso:5, min:0, max:120, f:0},
  7: {t:"Cuando inyectar", k:"lista", s:"CO2", op:["Siempre, tambien de noche","Solo con luz encendida","Fotoperiodo (recomendado)"]},
  8: {t:"Techo de higiene", k:"num", s:"CO2", paso:100, min:0, max:2500, f:7},
  9: {t:"Temp maxima de dia", k:"num", s:"Temperatura y humedad de sala", paso:5, min:100, max:500, f:1},
  10: {t:"Temp maxima de noche", k:"num", s:"Temperatura y humedad de sala", paso:5, min:100, max:500, f:1},
  11: {t:"Hum maxima de dia", k:"num", s:"Temperatura y humedad de sala", paso:10, min:200, max:1000, f:1},
  12: {t:"Hum maxima de noche", k:"num", s:"Temperatura y humedad de sala", paso:10, min:200, max:1000, f:1},
  13: {t:"Usar consigna de noche", k:"llave", s:"Temperatura y humedad de sala"},
  14: {t:"Temperatura", k:"num", s:"Temperatura y humedad de sala", paso:2, min:2, max:50, f:1},
  15: {t:"Humedad", k:"num", s:"Temperatura y humedad de sala", paso:5, min:5, max:200, f:1},
  16: {t:"Fotoperiodo encendido", k:"llave", s:"Fotoperiodo"},
  17: {t:"Enciende a las", k:"num", s:"Fotoperiodo", paso:15, min:0, max:1425, f:2},
  18: {t:"Apaga a las", k:"num", s:"Fotoperiodo", paso:15, min:0, max:1425, f:2},
  19: {t:"Rampa de subida", k:"num", s:"Fotoperiodo", paso:5, min:0, max:120, f:0},
  20: {t:"Brillo (%)", k:"num", s:"Fotoperiodo", paso:5, min:0, max:100, f:6},
  21: {t:"Riego automatico", k:"llave", s:"Que atiende cada demanda"},
  22: {t:"Cuantos minutos", k:"num", s:"CO2", paso:5, min:0, max:60, f:0},
  23: {t:"Interna", k:"lista", s:"Temperatura y humedad de sala", op:["Apagada","Siempre encendida","Por ventana horaria","Ciclica: marcha y pausa"]},
  24: {t:"Extraccion", k:"lista", s:"Temperatura y humedad de sala", op:["Apagada","Siempre encendida","Por ventana horaria","Ciclica: marcha y pausa"]},
  25: {t:"Temperatura alta - etapa 1", k:"lista", s:"Que atiende cada demanda", op:["libre","extraccion","ventilacion interna","aire acondicionado","calefaccion","deshumidificador","humidificador","VALVULA DE CO2","bomba de riego","luminarias","sirena","luz UV","luz roja","luz far red"]},
  26: {t:"Temperatura alta - etapa 2", k:"lista", s:"Que atiende cada demanda", op:["libre","extraccion","ventilacion interna","aire acondicionado","calefaccion","deshumidificador","humidificador","VALVULA DE CO2","bomba de riego","luminarias","sirena","luz UV","luz roja","luz far red"]},
  27: {t:"Humedad alta - etapa 1", k:"lista", s:"Que atiende cada demanda", op:["libre","extraccion","ventilacion interna","aire acondicionado","calefaccion","deshumidificador","humidificador","VALVULA DE CO2","bomba de riego","luminarias","sirena","luz UV","luz roja","luz far red"]},
  28: {t:"Humedad alta - etapa 2", k:"lista", s:"Que atiende cada demanda", op:["libre","extraccion","ventilacion interna","aire acondicionado","calefaccion","deshumidificador","humidificador","VALVULA DE CO2","bomba de riego","luminarias","sirena","luz UV","luz roja","luz far red"]},
  29: {t:"Entra a temp +", k:"num", s:"Temperatura y humedad de sala", paso:5, min:0, max:100, f:1},
  30: {t:"Entra a hum +", k:"num", s:"Temperatura y humedad de sala", paso:10, min:0, max:200, f:1},
  31: {t:"Grados", k:"num", s:"Temperatura y humedad de sala", paso:5, min:0, max:50, f:1},
  60: {t:"Temp minima", k:"num", s:"Avisos", paso:5, min:0, max:500, f:3, piso:50},
  61: {t:"Temp maxima", k:"num", s:"Avisos", paso:5, min:0, max:500, f:3, piso:50},
  62: {t:"Hum minima", k:"num", s:"Avisos", paso:10, min:0, max:1000, f:3, piso:50},
  63: {t:"Hum maxima", k:"num", s:"Avisos", paso:10, min:0, max:1000, f:3, piso:50},
  64: {t:"CO2 minimo", k:"num", s:"Avisos", paso:50, min:0, max:5000, f:4, piso:200},
  65: {t:"CO2 maximo", k:"num", s:"Avisos", paso:50, min:0, max:5000, f:4, piso:200},
  66: {t:"VPD minimo", k:"num", s:"Avisos", paso:5, min:0, max:400, f:5, piso:20},
  67: {t:"VPD maximo", k:"num", s:"Avisos", paso:5, min:0, max:400, f:5, piso:20},
  68: {t:"La ventana cuelga de", k:"lista", s:"Riego y sustrato", op:["El reloj","La luz"]},
  69: {t:"Esperar tras encender", k:"num", s:"Riego y sustrato", paso:15, min:0, max:720, f:0},
  70: {t:"Cada pulso dura (s)", k:"num", s:"Riego y sustrato", paso:30, min:30, max:1800, f:0},
  71: {t:"Pausa entre pulsos", k:"num", s:"Riego y sustrato", paso:15, min:15, max:720, f:0},
  72: {t:"Cuantos pulsos", k:"num", s:"Riego y sustrato", paso:1, min:0, max:20, f:0},
  73: {t:"Tipo de ciclo", k:"lista", s:"Fotoperiodo", op:["24 horas","Superciclo"]},
  74: {t:"Horas de luz (min)", k:"num", s:"Fotoperiodo", paso:30, min:60, max:1440, f:0},
  75: {t:"Horas oscuras (min)", k:"num", s:"Fotoperiodo", paso:30, min:60, max:1440, f:0},
  77: {t:"Enciende antes (min)", k:"num", s:"Fotoperiodo", paso:5, min:0, max:120, f:0},
  78: {t:"Sigue despues (min)", k:"num", s:"Fotoperiodo", paso:5, min:0, max:120, f:0},
  79: {t:"Hay sensor instalado", k:"llave", s:"Riego y sustrato"},
  80: {t:"El sustrato manda el riego", k:"llave", s:"Riego y sustrato"},
  81: {t:"Sustrato", k:"lista", s:"Riego y sustrato", op:["Coco/turba","Tierra"]},
  82: {t:"Objetivo (%)", k:"num", s:"Riego y sustrato", paso:10, min:0, max:1000, f:1},
  83: {t:"Dejar caer antes de regar", k:"num", s:"Riego y sustrato", paso:10, min:0, max:500, f:1},
  84: {t:"Tope de riegos por dia", k:"num", s:"Riego y sustrato", paso:1, min:0, max:48, f:0},
  85: {t:"Nodo Modbus", k:"num", s:"Riego y sustrato", paso:1, min:0, max:247, f:0},
  86: {t:"Luminaria", k:"lista", s:"Fotoperiodo", op:["Reles","5 canales"]},
  87: {t:"Nodo Modbus", k:"num", s:"Mezcla de espectro", paso:1, min:0, max:247, f:0},
  88: {t:"UV", k:"num", s:"Mezcla de espectro", paso:5, min:0, max:100, f:0},
  89: {t:"Azul", k:"num", s:"Mezcla de espectro", paso:5, min:0, max:100, f:0},
  90: {t:"Blanco", k:"num", s:"Mezcla de espectro", paso:5, min:0, max:100, f:0},
  91: {t:"Rojo", k:"num", s:"Mezcla de espectro", paso:5, min:0, max:100, f:0},
  92: {t:"Far red", k:"num", s:"Mezcla de espectro", paso:5, min:0, max:100, f:0},
  93: {t:"Temp minima de dia", k:"num", s:"Temperatura y humedad de sala", paso:5, min:0, max:400, f:3},
  94: {t:"Temp minima de noche", k:"num", s:"Temperatura y humedad de sala", paso:5, min:0, max:400, f:3},
  95: {t:"Humedad minima", k:"num", s:"Temperatura y humedad de sala", paso:10, min:0, max:900, f:3},
};
